/* eslint-disable */
/*Generated by GenDocu.com*/
// package: google.cloud.bigquery.storage.v1
// file: google/cloud/bigquery/storage/v1/annotations.proto

import * as jspb from "google-protobuf";
import * as google_protobuf_descriptor_pb from "google-protobuf/google/protobuf/descriptor_pb";

  export const columnName: jspb.ExtensionFieldInfo<string>;

